<?php
namespace App\Controller;
/**
 * Comments Controller
 *
 * @property \App\Model\Table\CommentsTable $Comments
 */
class CommentsController extends AuthMasterController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public $paginate = [
        'order' => [
            'Comments.title' => 'desc'
        ],
        'conditions' =>['del_flg' => false]
    ];
    public function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

    }
    public function getComment(){
        $this->request->allowMethod('ajax');
        $this->viewBuilder()->className('AdminTheme.Ajax');
        $id = $this->request->query('request_id');
        if (!$id) {
            throw new NotFoundException();
        }
        $arrComment =  $this->Comments->find()->contain(['Profiles','Users'])->where(['req_id' => $id])->all()->toArray();
        foreach ($arrComment as $key => $item){
            $arrComment[$key]->username = isset($item->profile->first_name) ? $item->profile->last_name.' '.$item->profile->first_name : $item->user->username;
            unset($arrComment[$key]->user);
        }
        $this->set(compact('arrComment'));
        $this->set('_serialize', 'arrComment');
    }
}
