<?php
namespace App\Controller;
/**
 * Comments Controller
 *
 * @property \App\Model\Table\CommentsTable $Comments
 */
class CommentsController extends AuthMasterController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public $paginate = [
        'order' => [
            'Comments.title' => 'desc'
        ],
        'conditions' =>['del_flg' => false]
    ];
    public function  initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        $depart = $this->Departments->newEntity();
//        $departments = $this->paginate($this->Departments);
        $this->set(compact('departments'));
        $this->set(compact('depart'));
        $this->set('_serialize', ['departments','depart']);

    }
}
