<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\User;
use Cake\Controller\Component\AuthComponent;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

/**
 * Login Controller
 *
 * @property \App\Model\Table\UsersTable $Login
 */
class HomeController extends AppController
{
//    private $User;
    public function  initialize()
    {
//        $this->User = TableRegistry::get('Users');
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function beforeFilter(Event $event)
    {
//        echo 123;exit;
        parent::beforeFilter($event);
        // Allow users to register and logout.
        // You should not add the "login" action to allow list. Doing so would
        // cause problems with normal functioning of AuthComponent.
        $this->Auth->allow(['login', 'logout']);
    }

    /**
     * Login method
     *
     *
     */
    public function login()
    {
        $this->viewBuilder()->layout('login');
        if ($this->request->is('post')) {

            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
    }
    public function index()
    {
//        $this->set('users1', $this->User->find('all'));
//        $this->set('_serialize', ['users1']);
//
//        $userTbl = TableRegistry::get('Users');
////        print_r($userTbl);exit;
//        $author = $userTbl->findByUsername('sonns')->first();
////        print_r($author);exit;
//        echo 123;exit;
    }





    /**
     * Logout method
     *
     *
     */
    public function logout()
    {
        return $this->redirect($this->Auth->logout());
    }

    /**
     * Logout method
     *
     *
     */
    public function register()
    {
        $user = $this->User->newEntity();
        if ($this->request->is('post')) {
            $user = $this->User->patchEntity($user, $this->request->data);
            if ($this->User->save($user)) {
                $this->Flash->success(__('The user has been saved.'));
                return $this->redirect(['action' => 'login']);
            }
            $this->Flash->error(__('Unable to add the user.'));
        }
        $this->set('user', $user);
    }

}
