<?php
namespace App\Controller;
use Aura\Intl\Exception;
use Notification\Utility\NotificationManager;

use Cake\Core\Configure;
use Cake\Network\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;
use Cake\Event\Event;


use ElephantIO\Client as Elephant;
use ElephantIO\Engine\SocketIO\Version1X;
use ElephantIO\Exception\ServerConnectionFailureException;
/**
 * Roles Controller
 *
 * @property \App\Model\Table\RolesTable $Roles
 */
class NotificationsController extends AuthMasterController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('Notification.Notification');

    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {

//        $notificationManager = NotificationManager::instance();
//        $notificationManager->addTemplate(
//            'newBlog', [
//                'title' => 'New blog by :username',
//                'body' => ':username has posted a new blog named :name'
//            ]
//        );
//
//        $notificationManager->notify([
//            'users' => [1, 2, 3, 4, 5],
//            'recipientLists' => ['administrators'],
//            'template' => 'newBlog',
//            'vars' => [
//                'username' => 'Bob Mulder',
//                'name' => 'My great new blogpost'
//            ]
//        ]);

//         $alert = $this->Notification->getNotifications();
//        echo '<pre>';
//        print_r($alert);
//        echo '</pre>';
//        exit;
//        $this->Notification->getNotifications;
//        $notificationManager->addTemplate('newBlog', [
//            'title' => 'New blog by :username',
//            'body' => ':username has posted a new blog named :name'
//        ]);

    }
    public function push(){
        if($this->request->is('post'))
        {
            $Elephant = new Elephant(new Version1X('http://localhost:5000'));
            try {
                $Elephant->initialize();
                $Elephant->emit('cake_event',[ 'arg' => $this->request->data['message'] ]);
                $Elephant->close();
                $this->Flash->success(__('Message sent.'));
            } catch (ServerConnectionFailureException $e) {
                $this->Flash->error(__('An error occurred while trying to establish a connection to the server.'));
            }
        }
    }
}
