<?php
namespace App\Controller;
use Cake\I18n\Time;
use Cake\Network\Exception\NotFoundException;
use Cake\ORM\TableRegistry;
use Cake\Routing\Router;

/**
 * Base Controller
 *
 * @property \App\Model\Table\RequestsTable $Requests
 */
class RequestsController extends AuthMasterController
{
    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
//    public $paginate = [
//        'limit' => 4,
//        'finder' => 'orWhere',
//        'order' => [
//            'Requests.id' => 'desc'
//        ],
//        'contain' =>[
//            'Users'=>array('fields'=>['username']),
//            'Departments' =>['fields'=>['name']],
//            'Categories' => ['fields'=>['name']]
//        ]
//    ];
    public $paginate = [
        'limit' => 20,
        'finder' => 'requestList',
        'order' => [
            'Requests.id' => 'desc'
        ]
    ];
    public  function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }


    public function index()
    {


        $roles = TableRegistry::get('Categories');
        $listCate = $roles->find('list', [
            'keyField' => 'id',
            'valueField' => 'name',
            'conditions' => ''
        ]);

        $conditions = [];
        if($this->user->role[0]->name ==='staff') {
            $conditions = ['group'=>['Requests.id Having Requests.user_id = '.$this->user->id.''],'conditions' => ['OR'=> ['Requests.status ' => 1]]];
        }elseif ($this->user->role[0]->name ==='top'){
            $conditions = ['group'=>['Requests.id Having manager_status = 1 or Requests.user_id = '.$this->user->id.' OR Requests.is_report = 1'],'conditions' => ['OR'=> ['Requests.status ' => 1]]];
        }elseif ($this->user->role[0]->name ==='manager'){
            $conditions = ['group'=>
                ['Requests.id Having (department_id = 2 and role_name ="staff" or Requests.user_id = '.$this->user->id.')
            or ( department_id <> 2  and sub_manager_status = 1 or Requests.user_id = '.$this->user->id.' )'],'conditions' => ['OR'=> ['Requests.status ' => 1]]];
        }
        elseif ($this->user->role[0]->name ==='sub-manager'){
            $conditions = ['group'=>['Requests.id Having  department_id <> 2 and role_name =\'staff\' and department_id = '.$this->user->dep_id.' or Requests.user_id = '.$this->user->id.' '],'conditions' => ['OR'=> ['Requests.status ' => 1]]];
        }else{
            $conditions = [];
        }
        $requests = $this->paginate($this->Requests,$conditions);
//        print_r($requests);exit;
//        echo '<pre>';print_r($requests) ; echo '</pre>';exit;
        $this->set(compact('requests'));
        $this->set(compact('listCate'));
        $this->set('_serialize', ['requests']);
        $this->set('_serialize', ['listCate']);
    }
    protected function _checkHead($data){
        if($data['id'] === 2 )
            return true;
        else{
            return false;
        }
    }
    /**
     * View method
     *
     * @param string|null $id Base id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {


    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $roles = TableRegistry::get('Categories');
        $listCate = $roles->find('list', [
            'keyField' => 'id',
            'valueField' => 'name',
            'conditions' => ''
        ]);
        $request = $this->Requests->newEntity();
        if ($this->request->is('post')) {

            //Check if image has been uploaded
            if (!empty($this->request->data['fileAttach']['name'])) {
                $file = $this->request->data['fileAttach'];

                $ext = substr(strtolower(strrchr($file['name'], '.')), 1);
                $arr_ext = array('jpg', 'jpeg', 'gif','png');
                if (in_array($ext, $arr_ext)) {
                    $path =  WWW_ROOT . 'file\request\\';
                    if(!is_dir($path)){
                        mkdir($path, 777,true);
                    }
                    move_uploaded_file($file['tmp_name'], $path . $file['name']);
                    //prepare the filename for database entry
                    $this->request->data['attach'] = $file['name'];
                }
            }
            $this->request->data['user_id'] = $this->user->id;
            $this->request->data['dep_id'] = $this->user->dep_id;
            $this->request->data['txtApproveDate'] = Time::parse($this->request->data['txtApproveDate']);
//            echo '<pre>';
//            print_r($this->request->data);
//            echo '</pre>';
//            exit;
            $request = $this->Requests->patchEntity($request, $this->request->data);
            if ($this->Requests->save($request)) {
                $this->Flash->success(__('The base has been saved.'));
                return $this->redirect(['action' => 'add']);
            } else {
                $this->Flash->error(__('The base could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('request'));
        $this->set(compact('listCate'));
        $this->set('_serialize', ['request']);
        $this->set('_serialize', ['listCate']);
    }
    public function addRequest()
    {
        if($this->request->is('ajax')){
            $request = $this->Requests->newEntity();
            $result = [];
            if ($this->request->is('post')) {
                //Check if image has been uploaded
                if (!empty($this->request->data['fileAttach']['name'])) {
                    $file = $this->request->data['fileAttach'];

                    $ext = substr(strtolower(strrchr($file['name'], '.')), 1);
                    $arr_ext = array('jpg', 'jpeg', 'gif','png');
//                    if (in_array($ext, $arr_ext)) {
                    if (true) {
                        $path =  WWW_ROOT . 'file\request\\';
                        if(!is_dir($path)){
                            mkdir($path, 777,true);
                        }
                        move_uploaded_file($file['tmp_name'], $path . $file['name']);
                        //prepare the filename for database entry
                        $this->request->data['attach'] = $file['name'];
                    }
                }
                $this->request->data['user_id'] = $this->user->id;
                $this->request->data['dep_id'] = $this->user->dep_id;
                $request->status = 1;
                $this->request->data['txtApproveDate'] = Time::parse($this->request->data['txtApproveDate']);
                $request = $this->Requests->patchEntity($request, $this->request->data);
                $request = $this->Requests->save($request);
                if ($request) {
                    $this->pushNotification($request,'add');
                    $result  = ['params'=>$request , 'status' => 'Success' , 'response'=> __('The request has been saved.')];
                } else {
                    $result  = ['params'=>$request , 'status' => 'Error' , 'response'=> __('The request could not be saved. Please, try again or contact for admin page.')];
                }
            }
            $this->set(compact('result'));
            $this->set('_serialize', ['result']);
        }
    }
    private function pushNotification($request,$mode, $is_approve = true){
        if($mode === 'add'){
            if(isset($this->user->role[0]->name) && $this->user->role[0]->name === 'staff'){
                $this->Notification->notify([
                    'recipientLists' => ($this->user->dep->name === 'Headquarter') ? ['manager'] : ['sub-manager'],
                    'template' => ['notifierRequest'],
                    'is_approve' => $is_approve,
                    'message' => [
                        'username' => $this->user->profile->first_name . ' ' .$this->user->profile->last_name,
                        'title' => $request->title,
                        'category' => 'Request',
                        'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview', $request->id),true)
                    ]
                ]);
            }
            else if(isset($this->user->role[0]->name) && $this->user->role[0]->name === 'sub-manager'){
                $this->Notification->notify([
                    'recipientLists' => ['manager'],
                    'template' => ['notifierRequest'],
                    'is_approve' => $is_approve,
                    'message' => [
                        'username' => $this->user->profile->first_name . ' ' .$this->user->profile->last_name,
                        'title' => $request->title,
                        'category' => 'Request',
                        'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview',  $request->id),true)
                    ]
                ]);
            }else if(isset($this->user->role[0]->name) && $this->user->role[0]->name === 'manager'){
                $this->Notification->notify([
                    'recipientLists' => ['top'] ,
                    'template' => ['notifierRequest'],
                    'is_approve' => $is_approve,
                    'message' => [
                        'username' => $this->user->profile->first_name . ' ' .$this->user->profile->last_name,
                        'title' => $request->title,
                        'category' => 'Request',
                        'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview', $request->id),true)
                    ]
                ]);
            }else{
                //nothing
            }
        }
        elseif($mode === 'report'){
            $this->Notification->notify([
                'recipientLists' =>  ['top'],
                'template' => ['notifierRequest'],
                'is_approve' => $is_approve,
                'message' => [
                    'username' => $this->user->profile->first_name . ' ' .$this->user->profile->last_name,
                    'title' => $request->title,
                    'category' => 'Request',
                    'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview', $request->id),true)
                ]
            ]);
        }
        elseif($mode === 'changeStatus'){
            $topInfo = $this->Notification->getRecipientList('top');
            $managerInfo = $this->Notification->getRecipientList('manager');
            if(count($topInfo)){
                $top_name = (empty($topInfo[0]->first_name)) ? $topInfo[0]->username : $topInfo[0]->first_name . $topInfo[0]->last_name;
            }else{
                $top_name = '';
            }
            if(count($managerInfo)){
                $manager_name = (empty($managerInfo[0]->first_name)) ? $managerInfo[0]->username : $managerInfo[0]->first_name . $managerInfo[0]->last_name;
            }else{
                $manager_name = '';
            }
            if($this->user->dep->name === 'Headquarter'){
                $recipientLists = ['top','manager'];
                $sub_manager_name = '';
            }else{
                $recipientLists = ['top','manager','sub-manager'];
                $subManagerInfo = $this->Notification->getRecipientList('sub-manager');
                if(count($subManagerInfo)){
                    $sub_manager_name = (empty($subManagerInfo[0]->first_name)) ? $subManagerInfo[0]->username : $subManagerInfo[0]->first_name . $subManagerInfo[0]->last_name;
                }else{
                    $sub_manager_name = '';
                }
            }
           if(isset($this->user->role[0]->name) && $this->user->role[0]->name === 'sub-manager'){
                // notify for user
                $this->Notification->notify([
                    'users' => [$request->user_id],
                    'recipientLists' => ['manager'],
                    'template' => ['notifierBySubManager'],
                    'is_approve' => $is_approve,
                    'message' => [
                        'subManagerName' => $sub_manager_name,
                        'username' => isset($request->profile->first_name) ? $request->profile->first_name . ' ' . $request->profile->last_name : $request->user->username,
                        'title' => $request->title,
                        'category' => 'Request',
                        'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview',  $request->id),true)
                    ]
                ]);
            }else if(isset($this->user->role[0]->name) && $this->user->role[0]->name === 'manager'){
                // notify for user and sub-manager
                $this->Notification->notify([
                    'users' => [$request->user_id],
                    'recipientLists' => (in_array("sub-manager", $recipientLists)) ? ['top','sub-manager'] : ['top'],
                    'template' => ['notifierByManager'],
                    'is_approve' => $is_approve,
                    'message' => [
                        'managerName' => $manager_name,
                        'subManagerName' =>$sub_manager_name,
                        'username' => isset($request->profile->first_name) ? $request->profile->first_name . ' ' . $request->profile->last_name : $request->user->username,
                        'title' => $request->title,
                        'category' => 'Request',
                        'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview',  $request->id),true)
                    ]
                ]);
            }else if(isset($this->user->role[0]->name) && $this->user->role[0]->name === 'top'){
                // notify for user and sub-manager and manager
                $this->Notification->notify([
                    'users' => [$request->user_id],
                    'recipientLists' => (in_array("sub-manager", $recipientLists)) ? ['manager','sub-manager'] : ['manager'],
                    'template' => ['notifierByTop'],
                    'is_approve' => $is_approve,
                    'message' => [
                        'topName' => $top_name,
                        'managerName' => $manager_name,
                        'subManagerName' =>$sub_manager_name,
                        'username' => isset($request->profile->first_name) ? $request->profile->first_name . ' ' . $request->profile->last_name : $request->user->username,
                        'title' => $request->title,
                        'category' => 'Request',
                        'link' => Router::url(array('controller'=>'Requests', 'action'=>'preview', $request->id),true)
                    ]
                ]);
            }
            else{
                //nothing
            }
        }
    }
    public function changeStatus(){
        $this->request->allowMethod('ajax');
        $id = $this->request->query('request_id');
        $mod = $this->request->query('mod') ;
        if (!$id || !$this->request->query('mod')) {
            throw new NotFoundException();
        }
        if($mod === 'app' || $mod === 'rej'){
            $request = $this->Requests->find()->where(['Requests.id' => $id])
                ->contain(['Profiles', 'Users'])->first();
            if (!count($request)) {
                throw new NotFoundException();
            }
            $approval = TableRegistry::get('Approvals');
            $approvalInfo = $approval->find()->where(['user_id'=>$this->user->id,'req_id'=>$id])->first();

            if($mod !== 'app' && $mod !== 'rej'){
                $request->status = 0;
            }
            else{
                if(!count($approvalInfo)){
                    $approvalE = $approval->newEntity();
                    $approvalE->user_id = $this->user->id;
                    $approvalE->req_id = $id;
                    $approvalE->role_id = $this->user->role[0]->id;
                    $approvalE->status = ($mod === 'app' ) ? 'approved' : 'rejected' ;
                    $approval->save($approvalE);
                    //add push noti
                    $this->pushNotification($request,'changeStatus',$mod === 'app' );

                }else{
                    throw new NotFoundException();
                }
            }
            if($this->Requests->save($request)){
                $result = $this->responseData(true,['id'=>$request->id]);
            }else{
                throw new NotFoundException();
            }

        }elseif($mod === 'report'){
            $request = $this->Requests->find()->where(['Requests.id' => $id])
                ->contain(['Profiles', 'Users'])->first();
            if (!count($request)) {
                throw new NotFoundException();
            }
            $request->is_report = 1;
            if($this->Requests->save($request)){
                $this->pushNotification($request,'report' );
                $result = $this->responseData(true,['id'=>$request->id]);
            }else{
                throw new NotFoundException();
            }
        }
        elseif($mod === 'multiDel' || $mod === 'multiApp'|| $mod === 'multiRej'){
            if($mod === 'multiApp'){
                throw new NotFoundException();
            }elseif ($mod === 'multiRej'){
                throw new NotFoundException();
            }else{
                throw new NotFoundException();
            }
            $arrId = explode(',',$id);
            $temp = $this->Requests->updateAll(['status'=> $status],['id IN'=>$arrId]);
            $result = $this->responseData(true,$temp);
        }
        $this->set(compact('result'));
        $this->set('_serialize', ['result']);
    }
    /**
     * Edit method
     *
     * @param string|null $id Base id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $base = $this->Base->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $base = $this->Base->patchEntity($base, $this->request->data);
            if ($this->Base->save($base)) {
                $this->Flash->success(__('The base has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The base could not be saved. Please, try again.'));
            }
        }
        $this->set(compact('base'));
        $this->set('_serialize', ['base']);
    }
    public function preview1($id = null){
        $tblApproval = TableRegistry::get('Approvals');
        $approvals =  $tblApproval->find()->where(['req_id'=>$id])->contain(['Requests'=>['Users','Profiles','Departments','Categories'],'Roles','Profiles','Users'])->all()->toArray();
        if(count($approvals)){
            $result = [];

            foreach($approvals as $app){

                if(!count($result)){
                    $result = $app->request;

                    $result['alias_name']= (isset($app->request->profile->first_name)) ? $app->request->profile->first_name. ' ' . $app->request->profile->last_name : $app->request->user->username;
                }
                echo '<pre>';
                print_r($app);
                echo '</pre>';
                exit;

                $result['categories_name'] = $app->request->category->name;
                $result['department_name'] = $app->request->department->name;
                if($app->role->name === 'manager'){
                    $result['manager_name'] = (isset($app->profile->first_name)) ? $app->profile->first_name.' '. $app->profile->last_name :  $app->user->username ;
                    $result['manager_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }elseif ($app->role->name === 'top'){
                    $result['top_name'] = (isset($app->profile->first_name)) ? $app->profile->first_name.' '. $app->profile->last_name :  $app->user->username;
                    $result['top_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }else{
                    $result['sub_name'] = (isset($app->profile->first_name)) ? $app->profile->first_name.' '. $app->profile->last_name :  $app->user->username;
                    $result['sub_manager_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }
            }
            echo '<pre>';
            print_r($result);
            echo '</pre>';
            exit;
            $this->set('requestDetail',$result);
        }else{
            $requestDetail = $this->Requests->find('requestList')->where(['Requests.id'=>$id])->groupBy('Requests.id')->first();
            echo '<pre>';
            print_r($requestDetail);
            echo '</pre>';
            exit;
            if(!count($requestDetail[0]))
            {
                throw new NotFoundException;
            }

            $this->set('requestDetail',$requestDetail[0]);

        }
        $this->set('_serialize', ['requestDetail']);
    }

    public function preview($id = null){
        $requestDetail = $this->Requests->find('requestList')->where(['Requests.id'=>$id])->groupBy('Requests.id')->first();
        if(!count($requestDetail[0]))
        {
            throw new NotFoundException;
        }
        $result = $requestDetail[0];
        $tblApproval = TableRegistry::get('Approvals');
        $approvals =  $tblApproval->find()->where(['req_id'=>$id])->contain(['Roles','Profiles','Users'])->all()->toArray();
        $result['app_status'] = 0;
        if(count($approvals)){
            foreach($approvals as $app){
                if($this->user->role[0]->name === $app->role->name){
                    $result['app_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }
                if($app->role->name === 'manager'){

                    $result['manager_name'] = (isset($app->profile->first_name)) ? $app->profile->first_name.' '. $app->profile->last_name :  $app->user->username ;
                    $result['manager_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }elseif ($app->role->name === 'top'){
                    $result['top_name'] = (isset($app->profile->first_name)) ? $app->profile->first_name.' '. $app->profile->last_name :  $app->user->username;
                    $result['top_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }else{
                    $result['sub_name'] = (isset($app->profile->first_name)) ? $app->profile->first_name.' '. $app->profile->last_name :  $app->user->username;
                    $result['sub_manager_status'] = ($app->status === 'approved') ? 1 : 2 ;
                }
            }
        }
//        echo '<pre>';
//        print_r($this->user);
//        echo '</pre>';
//        exit;
        $this->set('requestDetail',$result);
        $this->set('_serialize', ['requestDetail']);
    }
    /**
     * Delete method
     *
     * @param string|null $id Base id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $base = $this->Base->get($id);
        if ($this->Base->delete($base)) {
            $this->Flash->success(__('The base has been deleted.'));
        } else {
            $this->Flash->error(__('The base could not be deleted. Please, try again.'));
        }
        return $this->redirect(['action' => 'index']);
    }
}
