<?php
namespace App\Controller;
use Cake\Core\Configure;
use SpcAuth\Auth\SpcAuthorize;

/**
 * Roles Controller
 *
 * @property \App\Model\Table\RolesTable $Roles
 */
class RolesController extends AuthMasterController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->loadComponent('MyAuth',[
           'className'=>'SpcAuth.Auth',
            'autoClearCache' =>Configure::read('debug'),
            'mode' =>false,
        ]);
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
//        print_r($this->MyAuth->getACL());exit;
        $this->set('roles', $this->Roles->find('all'));
        $this->set('listAcl', $this->MyAuth->getACL());
        $this->set('_serialize', ['roles']);
    }

    /**
     * View method
     *
     * @param string|null $id Role id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function view($id = null)
    {
//
//        $role = $this->Roles->get($id, [
//            'contain' => []
//        ]);
//
//        $this->set('role', $role);
//        $this->set('_serialize', ['role']);
    }
}
