<?php
use Migrations\AbstractMigration;

class TblMasterPermissions extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function up()
    {
        $roles = $this->table('tbl_master_permissions', [
            'id' => false,
            'primary_key' => ['id']
        ]);
        $roles->addColumn('id', 'integer', [
            'autoIncrement' => true,
            'default' => null,
            'limit' => 11,
            'null' => false,
        ]) ->addPrimaryKey(['id'])
            ->addColumn('name', 'string', array('limit' => 255))
            ->addColumn('display_name', 'string', array('limit' => 100))
            ->addColumn('created', 'datetime',['default'=> "CURRENT_TIMESTAMP"])
            ->addColumn('modified', 'datetime', array('null' => true,'default'=>null))
            ->save();
    }
    public function down()
    {
        $this->table('tbl_master_permissions')->drop();
        parent::down(); // TODO: Change the autogenerated stub
    }
}
